server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://124.70.185.116:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          num-batch: 512
        model: nomic-embed-text
#      chat:
#        enabled: false
    openai:
      base-url: https://key.wenwen-ai.com/
      api-key: sk-6V2exWFBSa2lmuZ7C0D773D1BaEd4fB7A1B6A0A265D550C6
      embedding-model: text-embedding-ada-002
    deepseek:
      enabled: true
      base-url: https://api.deepseek.com/v1
      api-key: sk-329ec42fccd1436e8cbd1814c9cf031a
      embedding-model: deepseek-embed-v1
    rag:
      embed: nomic-embed-text #nomic-embed-text、text-embedding-ada-002
    ai:
      transformers:
        enabled: false

# Redis
redis:
  sdk:
    config:
#      host: 124.70.185.116
      host: 172.24.58.32
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true
      password: gwh842

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
#ai:
#  chatglm:
#    api-key: f93b8a992cd743c0a6d52949156a4372.wVJRhfe6KmOSbLzL
#    base-url: https://open.bigmodel.cn
#    embedding-model:  chatglm-embedding-v2
#    enabled: true
#  deepseek:
#    api-key: sk-329ec42fccd1436e8cbd1814c9cf031a
#    base-url: https://api.deepseek.com/v1
#    embedding-model: deepseek-embed-v1
#    enabled: true
#  ollama:
#    embedding-model: text-embedding-ada-002
#    base-url:  http://localhost:11434
#    enabled: true

