name: Test API Connection

on: 
  push:  # 当代码推送到 main 分支时触发
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  your_job:
    runs-on: self-hosted  # 运行在自托管 Runner 上

    steps:
      - name: Test API Connection
        run: |
          curl http://117.72.115.188:11434/api/generate \
            -H "Content-Type: application/json" \
            -d '{
                  "model": "deepseek-r1:1.5b",
                  "prompt": "1+1",
                  "stream": false
                }'
