name: Test Ollama Integration

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test-ollama-api:
    runs-on: self-hosted
    steps:
      - name: Fix Path Conversion
        shell: bash
        run: |
          $tempPath = "D:\github\actions-runner\_work\_temp"
          $correctPath = $tempPath -replace "\\", "/"
          Write-Host "Corrected Path: $correctPath"

      - name: Test API connection
        shell: bash
        run: |
          response=$(curl -s -X POST http://localhost:11434/api/generate \
            -H "Content-Type: application/json" \
            -d '{
                  "model": "deepseek-r1:1.5b",
                  "prompt": "1+1",
                  "stream": false
                }' \
            --connect-timeout 30 \
            --max-time 60)
          
          if [ $? -ne 0 ]; then
            echo "API request failed with exit code $?"
            exit 1
          fi
          
          echo "API Response: $response"
