name: Test Local API

on: [workflow_dispatch]  # 手动触发

jobs:
  test-api:
    runs-on: self-hosted  # 必须使用自托管 Runner
    steps:
    - name: Test POST Request
      run: |
        # 发送请求并检查状态码是否为200
        if ! curl -sS -X POST http://localhost:11434/api/generate \
          -H 'Content-Type: application/json' \
          -d '{"model":"deepseek-r1:1.5b","prompt":"1+1","stream":false}' \
          -w "\nStatus Code: %{http_code}\n" \
          --fail; then
          echo "❌ 请求失败"
          exit 1
        fi
